import PageHeader from '../components/PageHeader'
import { Link } from 'react-router-dom'

const PRINCIPLES = [
  {
    icon: '🔍',
    title: 'Transparency',
    color: 'blue',
    points: [
      'EcoPlate AI clearly indicates whether it is running in Demo Mode or connected to a live AI provider.',
      'The waste percentage formula is shown openly on the Analyzer page: (Leftover ÷ Prepared) × 100.',
      'Severity thresholds (Low / Moderate / High) are labelled as prototype values, not official standards.',
      'AI-generated recommendations are always identified as AI output, never presented as authoritative guidance.',
      'The system prompt that guides the AI is documented in the backend source code for anyone to inspect.',
    ],
  },
  {
    icon: '🔒',
    title: 'Privacy',
    color: 'green',
    points: [
      'EcoPlate AI does not collect, store, or transmit any personal information about students or staff.',
      'Waste data entered into the Analyzer is sent only to the backend for AI processing and is not persisted.',
      'No user accounts, cookies, or tracking mechanisms are used.',
      'Chat messages are held in browser memory only and cleared when the page is refreshed or the chat is reset.',
      'If you add an OpenAI API key, data is transmitted to OpenAI under their privacy policy — review it before deployment.',
    ],
  },
  {
    icon: '👤',
    title: 'Human Oversight',
    color: 'purple',
    points: [
      'All AI recommendations are explicitly labelled as suggestions that require review by canteen staff.',
      'The system is designed to support human decision-making, not replace it.',
      'Canteen managers retain full authority over operational decisions; the AI provides one input among many.',
      'Staff with local knowledge of attendance patterns, events, and supplier constraints are best placed to evaluate suggestions.',
      'This prototype does not automate any purchasing, preparation, or operational processes.',
    ],
  },
  {
    icon: '⚠️',
    title: 'Limitations',
    color: 'amber',
    points: [
      'This is an academic prototype. It has not been validated in a real institutional setting.',
      'AI recommendations may not account for local context, cultural food preferences, or seasonal variation.',
      'The AI does not invent statistics, but may occasionally produce responses that are incomplete or imprecise.',
      'Demo Mode responses are pre-written examples, not generated by a live AI model.',
      'Waste severity thresholds are illustrative only and should not be used for compliance or reporting purposes.',
      'A small dataset or a single day of data is not sufficient to draw reliable conclusions about waste patterns.',
    ],
  },
]

const COLOR_MAP = {
  blue:   { bg: 'bg-blue-50',   border: 'border-blue-100',  icon: 'bg-blue-100 text-blue-700',  title: 'text-blue-800',  dot: 'bg-blue-400'   },
  green:  { bg: 'bg-eco-50',    border: 'border-eco-100',   icon: 'bg-eco-100 text-eco-700',    title: 'text-eco-800',   dot: 'bg-eco-500'    },
  purple: { bg: 'bg-purple-50', border: 'border-purple-100',icon: 'bg-purple-100 text-purple-700', title: 'text-purple-800', dot: 'bg-purple-400' },
  amber:  { bg: 'bg-amber-50',  border: 'border-amber-100', icon: 'bg-amber-100 text-amber-700', title: 'text-amber-800', dot: 'bg-amber-400'  },
}

function PrincipleCard({ icon, title, color, points }) {
  const c = COLOR_MAP[color]
  return (
    <div className={`rounded-2xl border p-6 ${c.bg} ${c.border}`}>
      <div className="flex items-center gap-3 mb-4">
        <div className={`w-10 h-10 rounded-xl flex items-center justify-center text-xl ${c.icon}`}>
          {icon}
        </div>
        <h2 className={`text-xl font-bold ${c.title}`}>{title}</h2>
      </div>
      <ul className="space-y-2.5">
        {points.map((point, i) => (
          <li key={i} className="flex items-start gap-2.5 text-sm text-gray-700 leading-relaxed">
            <span className={`w-1.5 h-1.5 rounded-full mt-1.5 shrink-0 ${c.dot}`} />
            {point}
          </li>
        ))}
      </ul>
    </div>
  )
}

export default function ResponsibleAI() {
  return (
    <div>
      <PageHeader
        icon="🛡️"
        title="Responsible AI"
        subtitle="How EcoPlate AI uses artificial intelligence ethically, transparently, and with appropriate safeguards."
      />

      <div className="max-w-5xl mx-auto px-4 sm:px-6 py-10 sm:py-14 space-y-10">

        {/* Intro */}
        <div className="card">
          <div className="flex items-start gap-4">
            <div className="text-3xl shrink-0">🌿</div>
            <div>
              <h2 className="text-xl font-bold text-gray-900 mb-2">Our commitment</h2>
              <p className="text-gray-600 leading-relaxed">
                EcoPlate AI is an academic prototype built to demonstrate how AI can support food waste
                reduction in institutional canteens. Because AI systems can influence decisions, we have
                designed this tool with four core principles in mind: <strong>transparency</strong>,{' '}
                <strong>privacy</strong>, <strong>human oversight</strong>, and honest acknowledgement
                of <strong>limitations</strong>.
              </p>
              <p className="text-gray-600 leading-relaxed mt-3">
                This page explains how each principle is applied in this project and what users should
                understand before relying on its output.
              </p>
            </div>
          </div>
        </div>

        {/* Four principle cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 stagger-children">
          {PRINCIPLES.map((p) => (
            <PrincipleCard key={p.title} {...p} />
          ))}
        </div>

        {/* How AI is used in this project */}
        <div className="card">
          <h2 className="section-title mb-4">How AI is used in this project</h2>
          <div className="space-y-4">
            {[
              {
                step: '1',
                title: 'Waste Analyzer — recommendation generation',
                body: 'When a user submits food waste data, the backend sends the food item name, prepared quantity, consumed quantity, leftover quantity, waste percentage, and severity level to an LLM (OpenAI GPT-4o-mini by default). The model returns a short, practical recommendation. In Demo Mode, pre-written example responses are used instead.',
              },
              {
                step: '2',
                title: 'AI Advisor — conversational assistance',
                body: 'The chat interface sends the user\'s message and the recent conversation history to the same LLM, guided by a system prompt that restricts responses to food waste, sustainability, and responsible consumption topics. The AI is instructed not to invent statistics and to acknowledge uncertainty.',
              },
              {
                step: '3',
                title: 'System prompt — scope control',
                body: 'A backend system prompt sets the context and rules for the AI: stay focused on food waste and sustainability, keep responses concise, do not invent statistics, and remind users that recommendations are suggestions. This prompt is visible in the open-source backend code.',
              },
            ].map(({ step, title, body }) => (
              <div key={step} className="flex gap-4">
                <div className="w-8 h-8 rounded-full bg-eco-600 text-white font-bold text-sm flex items-center justify-center shrink-0 mt-0.5">
                  {step}
                </div>
                <div>
                  <p className="font-semibold text-gray-800 mb-1">{title}</p>
                  <p className="text-sm text-gray-600 leading-relaxed">{body}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* What this tool does NOT do */}
        <div className="card border-red-100 bg-red-50">
          <h2 className="text-xl font-bold text-red-800 mb-4">What EcoPlate AI does NOT do</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {[
              'Collect or store personal student or staff information',
              'Make autonomous decisions about food preparation',
              'Guarantee waste reduction outcomes',
              'Provide professional nutrition, health, or regulatory advice',
              'Claim to represent official SDG measurement or reporting',
              'Present demo data as real institutional statistics',
              'Use facial recognition or biometric identification',
              'Connect to canteen management systems or POS data',
            ].map((item) => (
              <div key={item} className="flex items-start gap-2.5 text-sm text-red-700">
                <span className="text-red-400 mt-0.5 shrink-0">✕</span>
                {item}
              </div>
            ))}
          </div>
        </div>

        {/* Recommendations guidance */}
        <div className="card border-eco-200 bg-eco-50">
          <h2 className="text-xl font-bold text-eco-800 mb-3">Using AI recommendations responsibly</h2>
          <p className="text-sm text-eco-700 leading-relaxed mb-4">
            When you receive an AI recommendation from the Waste Analyzer or AI Advisor, treat it as
            one input — not a directive. The following steps support responsible use:
          </p>
          <ol className="space-y-3">
            {[
              'Review the recommendation with canteen staff who have operational context.',
              'Collect data over multiple days before drawing conclusions or making changes.',
              'Consider factors the AI cannot know: local events, menu changes, seasonal patterns.',
              'Test any proposed change on a small scale first and monitor the outcome.',
              'Document what worked and what did not — this builds institutional knowledge over time.',
            ].map((item, i) => (
              <li key={i} className="flex items-start gap-3 text-sm text-eco-700">
                <span className="w-6 h-6 rounded-full bg-eco-600 text-white text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">
                  {i + 1}
                </span>
                {item}
              </li>
            ))}
          </ol>
        </div>

        {/* Footer CTA */}
        <div className="text-center py-4">
          <p className="text-gray-500 text-sm mb-5">
            Have questions about how this prototype works? Explore the source code or try the tools.
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <Link to="/analyzer" className="btn-primary">📊 Try Waste Analyzer</Link>
            <Link to="/advisor"  className="btn-secondary">🤖 Ask AI Advisor</Link>
          </div>
        </div>

      </div>
    </div>
  )
}
